clone:
  path: github.com/drone/drone

build:
  test:
    image: drone/golang:1.5
    environment:
      - GO15VENDOREXPERIMENT=1
    commands:
      - make deps gen
      - make test test_postgres test_mysql
  dist:
    image: drone/golang:1.5
    environment:
      - GO15VENDOREXPERIMENT=1
    commands:
      - make build
    when:
      event: push

compose:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: fracting/drone
    tag: [ "latest", "0.4.2" ]
    when:
      repo: fracting/drone
      branch: [ "master", "upstream-0.4.2" ]
