clone:
  path: github.com/drone/drone

build:
  image: drone/golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - make deps gen
    - make test test_postgres test_mysql
    - make build build_static deb docs

compose:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: chat.freenode.net
      port: 6667

publish:
  docker:
    username: fracting
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: fracting/drone
    tag:
      - "latest"
      - "0.4"
    when:
      repo: fracting/drone
      branch: master
